language: node_js
node_js: 10
os: osx
env:
  - HOMEBREW_NO_AUTO_UPDATE="1"
if: (branch = master OR branch = develop)
addons:
  firefox: latest
before_install:
  - brew install geckodriver
install:
  - yarn install
script:
  - yarn build
  - mkdir -p public/uploads/png && mkdir -p public/uploads/mei
  - yarn start &
  - yarn test
