language: node_js
node_js: 
  - 10
  - 9
  - 8
matrix:
  include:
    # Mac Installation.
    - os: osx
      env:
        - HOMEBREW_NO_AUTO_UPDATE="1"
install:
  - brew install yarn geckodriver
  - yarn install
script:
  - yarn build
  - yarn start
  - yarn test
