language: node_js
node_js: 10
os: osx
env:
 - HOMEBREW_NO_AUTO_UPDATE="1"
install:
  - brew install yarn geckodriver
  - yarn install
script:
  - yarn build
  - mkdir -p public/uploads/png && mkdir -p public/uploads/mei
  - yarn start &
  - yarn test
